### ISSUE TITLE
`headache` should track the last "time" it ran

### ISSUE THREAD

**Issue by fbiville** [fbiville/headache#14]
Then, `headache` will only consider the files that changed since.
The `--init` option should be dropped then (`headache` will assume that it runs for the first time if the metadata is not present).

**Comment by glyn** [comment]
Yes, I think the idea of storing metadata in a file such as `.headache` would work nicely. It may even be sufficient just to `touch` that file on each run that actually changes a license header and then use the git history of the file to work out how far to go back next time `headache` is run.

**Comment by fbiville** [comment]
The file detection is implemented here: https://github.com/fbiville/headache/blob/master/core/configuration.go#L79-L108.

It populates `configuration#vcsChanges` which represent the set of files to run `headache` against.

- During dry-run / regular run, `headache` uses VCS information to know which files to change, based on a configurable [remote name and branch name](https://github.com/fbiville/headache/blob/master/core/configuration.go#L39-L40) (which is not a good solution btw and this issue will fix it).
 - During dry-run with `--init`, the files are matches from the local files matching the configured include and exclude patterns. 
 - During run with `--dump-file`, the filenames are extracted from the file passed as an argument.

Once this issue is implemented:
 - `--init` option can be dropped entirely, the fact that the metadata is not present is enough to run the same logic
- I'm not sure whether we'll still need the explicit `configuration#VcsRemote` and `configuration#VcsBranch` but [Vcs#GetVcsChanges](https://github.com/fbiville/headache/blob/master/versioning/vcs.go#L46) will need to change to be based on a previous SHA and not a static remote/branch

**Comment by fbiville** [comment]
@ntjnh let me know if you wanna work on this one
it's a bit more involved but I'm available to help!

**Comment by ntjnh** [comment]
Sounds like an interesting issue to tackle but unfortunately I don't know any Go at all 😕
