### ISSUE TITLE
Support date range of the form YYYY-Present

### ISSUE THREAD

**Issue by glyn** [fbiville/headache#43]
Some copyright lines are of the form YYYY-Present rather than YYYY-ZZZZ. For example:
```
Copyright (c) 2019-Present Pivotal Software, Inc. All Rights Reserved.
```

**Comment by jmelfi** [comment]
This would be a nice improvement! I was about to see what I needed to do for getting a range in for years. A StartYear and EndYear parameter would be perfect.

**Comment by fbiville** [comment]
Nice :) 
I will try to get that done this week, unless you want to give it a go @jmelfi?

**Comment by fbiville** [comment]
@jmelfi note that the range of years, as of today, is completely managed by headache by extracting the earliest and latest commit years of each file.
